### ISSUE TITLE
Feature request: subscribe to cotw by email

### ISSUE THREAD

**Issue by mireille-raad** [DCgov/econintel-cotw#2]
Hey :)

This is more a suggestion or feature request - can you add a subscribe by email to the cotw?

Cheers!

**Comment by mseew** [comment]
Thanks for your request! -- it's been added! See the bottom of the front page. Now to add an unsubscribe feature...

**Comment by mireille-raad** [comment]
Thanks! just subscribed :) 

Excited to be checking this regularly - great idea :D
